### ISSUE TITLE
Dashboard errrors partially hidden

### ISSUE THREAD

**Issue by tnelson-doghouse** [turbot/steampipe#2336]
**Describe the bug**
When there's a dashboard error, it doesn't always fit in the box in the UI.  

[https://files.slack.com/files-pri/T01SW2PU554-F03U433A5NW/image.png](https://files.slack.com/files-pri/T01SW2PU554-F03U433A5NW/image.png)

**Steampipe version (`steampipe -v`)**
Example: v0.15.4

**To reproduce**

- Create a dashboard with deeply nested containers
- Have the innermost container refer to something that doesn't exist.  Something like...

```
dashboard "name" {
    container {
        container {
            container {
                container {
                       query = sql.does_not_exist
                }
            }
        }
    }
}
```

**Expected behavior**
The popup box is wider, at least when the error is.  Or if necessary, there's a scroll bar.  

**Workaround**

If you do Inspect Element in your browser, you can see the error

**Comment by MichaelBurgess** [comment]
@tnelson-doghouse thanks for reporting this - these errors can get pretty long with deeply-nested panels (as you discovered!). I prefer not to scroll, so I've given the modal more room on larger desktops and have broken the content for the really long cases that would otherwise overflow. Will be in the next minor release `v0.16.0`.

**Comment by tnelson-doghouse** [comment]
Thanks!
