### ISSUE TITLE
GCP mod is not taking service account provided credentials

### ISSUE THREAD

**Issue by rohan-birtia** [turbot/steampipe#2608]
**Describe the bug**
As mentioned I have created a service account and provide json file path in gcp.spc . But getting lot of errors regarding json object.+

**Steampipe version (`steampipe -v`)**
0.16.4

**To reproduce**
1. create a service account and provide credentials as mentioned https://hub.steampipe.io/plugins/turbot/gcp

```
connection "gcp_my_other_project" {
  plugin      = "gcp"
  project     = "my-other-project"
  credentials = "/home/me/my-service-account-creds.json"
}
```

**poc**
![image](https://user-images.githubusercontent.com/110599270/198312204-98500de0-8f56-4d4e-8668-3d3cad9caafd.png)

**Comment by cbruno10** [comment]
Hi @rohan-birtia , it seems like you've added the GCP service account creds (or another set of creds) into the `~/.steampipe/config` directory as `creds.json`, can you please try moving that out of the `~/.steampipe` directory, updating your `~/.steampipe/config/gcp.spc` to point to its new location, and run the query again?

Steampipe only expects plugin configuration files ending in `.spc` to be in the `~/.steampipe/config` directory, which is why you're seeing those errors.

**Comment by rohan-birtia** [comment]
Thanks this works. I have provided viewer role, as there is no such role as "ReadOnly"  still getting permission error . Let me know what are the roles to be provided. 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/110599270/198349293-2cb5c187-69a0-4813-bb24-758e6f652fdf.png">

**Comment by cbruno10** [comment]
@rohan-birtia Thanks for reporting the doc error referencing `ReadOnly`, we'll get that fixed in an upcoming release.

I checked the `Viewer` role in one of my GCP projects, and it seems like it should grant access to that check you sent over, as it has the `resourcemanager.projects.getIamPolicy` permission, which is used by the API call we're making in https://github.com/turbot/steampipe-plugin-gcp/blob/659d434179affadd731497f2099c95009c7a23b5/gcp/table_gcp_audit_policy.go#L79:
```
resp, err := service.Projects.GetIamPolicy(project, &cloudresourcemanager.GetIamPolicyRequest{}).Context(ctx).Do()
```

Are there any other controls or queries that are failing with a 403 error?

**Comment by rohan-birtia** [comment]
As you can see in the above screenshot. It's wasn't even able to check a singel comaplaince check. I am created a service account and assigned roles. Am I missing something ?

**Comment by cbruno10** [comment]
@rohan-birtia In the screenshot above, I can only see 1 control. Can you please share a screenshot of the other controls in that benchmark and their results?

Also, can you please try running a query in a `steampipe query` session, like one of the queries from https://hub.steampipe.io/plugins/turbot/gcp/tables/gcp_compute_disk, and paste the full output here?

**Comment by rohan-birtia** [comment]
after running few quieries manually, steampipe check option is working. But few checks are giving permission error. Can you please mention in the document what permissions are required. I have given roles/compute.viewer and roles/cloudasset.viewer roles as of now.
![image](https://user-images.githubusercontent.com/110599270/200290615-3f32792b-6cb0-470c-9e12-74ef32d7b1aa.png)

**Comment by cbruno10** [comment]
@rohan-birtia We recommend adding the project level `Viewer` role, which grants read-only access to all services (or most) in the GCP project. The role is detailed in the first row in https://cloud.google.com/iam/docs/understanding-roles.

Can you please add that role and try running the checks again?
