### ISSUE TITLE
Is it possible to get network utilization reports through SQLite?

### ISSUE THREAD

**Issue by Niba-nazar** [turbot/steampipe#2793]
Hi,

I noticed that this steampipe uses Postgresql as its default database. I have access to the DB and could run queries on the schema.tables. Nevertheless, if it's possible, I'd like to receive network use information for our Digitalocean and AWS plugins via SQLite. If you people have any features for this, could you kindly let me know?

**Comment by pskrbasu** [comment]
Hi @Niba-nazar, steampipe uses a PostgreSQL database, and currently we don't have any bindings for SQLite. 

However, we would like to know and understand more about your use case, so let us know in the conversation in [our slack channel](https://steampipe.slack.com/archives/C01UECB59A7/p1669292206131539) so that we could help you find alternate ways to achieve your use case.

Thanks
