### ISSUE TITLE
Service start timeout should be configurable

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3038]
In https://github.com/turbot/steampipe/commit/5dc46c4e09e8691c18787a1e22c8cc22d5a02f96 we raised the service startup connection timeout to 30 seconds. This works in most use-cases, but still falls short when bringing up a service in nodes under pressure.

We need to add an option in the ENVIRONMENT and Config files so that this can be tweaked.

**Comment by vhadianto** [comment]
@binaek @johnsmyth can we also detect if Postgres is in auto-recovery mode and wait until it fully complete its work? That will be good if we can do this.

**Comment by binaek** [comment]
@vhadianto will take a look

**Comment by binaek** [comment]
> @binaek @johnsmyth can we also detect if Postgres is in auto-recovery mode and wait until it fully complete its work? That will be good if we can do this.

@vhadianto 

When waiting for Postgres to fully complete recovery, what do you think is a good timeout after which we stop waiting for recovery to finish? I suppose it needs to be something big (3 minutes?) but does it need tweaking?

Moreover, do you think it's worth having two separate timeouts? One for recovery and another for connection, or should we pull in both under the same timeout (the current behaviour - only there's no separate recovery mode detection)

**Comment by vhadianto** [comment]
I believe all timeout should be configurable, there's no "good timeout" setting since the factors impacting what is acceptable  differs widely from one situation to another.

I think if we should wait (without timeout) while Postgres is in recovery mode. We need to be able to tell our users that Postgres is in recovery mode so they can seek further help if it get "stuck" in recovery.
