### ISSUE TITLE
present common dimensions in a standard order

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#3158]
When I add `connection_name` as a common dimension, I can get different orderings of common dimensions across controls. Ideally it would always be the same, and would be the order in which I named them in spvars.

![image](https://user-images.githubusercontent.com/46509/220484682-a592f038-9396-4a3f-bcce-52ed6959b351.png)

**Comment by MichaelBurgess** [comment]
The dashboard UI is using the same logic as the CLI - that is, the order of the non-control field columns in the control results columns array are used as the order for the dimensions. In the examples above, the UI is presenting the columns in the order it received them for that control.

Looking into the AWS Thrifty mod it seems like the order should be consistent due to the use of locals to inject them into the queries.

I think we'll need @kaidaguerre to take a look and see why we might be getting different column ordering in the controls sent across the socket to the dashboard UI.

**Comment by cbruno10** [comment]
@kaidaguerre Have you had a chance to look at this issue at all? I'm running into the same issue as @judell where I have a few controls in a benchmark that have the same set of additional dimensions in the same order, but when running them in `steampipe dashboard`, they can come in different orders.

When I run through `steampipe check`, the order is preserved and consistent though.
