### ISSUE TITLE
Error: failed to refresh connections: pq: server "steampipe" does not exist

### ISSUE THREAD

**Issue by darrenlewisexperian** [turbot/steampipe#319]
**Describe the bug**
I've just installled Steampipe but I can't run any queries because it returns an error.

```
$ steampipe -v
steampipe version 0.3.0
$ steampipe plugin install steampipe
Installed plugin: steampipe v0.1.2
Documentation:    https://hub.steampipe.io/plugins/turbot/steampipe
$ steampipe query "select name from steampipe_registry_plugin;"
Error: failed to refresh connections: pq: server "steampipe" does not exist
```

**Steampipe version (`steampipe -v`)**
steampipe version 0.3.0

**To reproduce**
See above.

**Expected behavior**
Data should be returned.

**Additional context**
WSL is disabled on my company machine so I am running the latest Ubuntu docker image from Docker Hub and installing Steampipe on that and running it.

**Comment by e-gineer** [comment]
@darrenlewisexperian Thanks for reporting this and sorry for the inconvenience.

I've been able to reproduce, and we're currently investigating for a workaround / fix.

**Comment by e-gineer** [comment]
I believe we've nailed this one down! Beyond the gross-ness of crash on first install (sorry, ugh) ... the root cause is interesting.

We do a number of Postgres options when running to optimize performance, memory etc for our embedded foreign data wrapper. (We're pretty much running an in-memory Postgres DB.)

One setting, `synchronous_commits=off` was affecting the install process. Basically, we're installing the Postgres foreign data wrapper extension and then starting the foreign server. But, because we shut down the DB immediately after doing that in some cases it would not finish committing those changes. Then, the foreign server (called steampipe) was not installed the next time we'd run, so you'd get the error above.

We're running through the test & release process now, so hope to have v0.3.2 fixing this available soon. I'll follow up here once it's published and we've done a final install test.

**Comment by e-gineer** [comment]
@darrenlewisexperian @vielmetti

v0.3.2 is now available, and should work if you are doing a clean install. It does in my testing.

If you are having trouble from a previous install and still seeing the error above, then please delete your `~/.steampipe` directory and try again with something like:
```
# Kill any left over steampipe processes
pkill -f steampipe
# Delete the corrupted / bad install database
rm -rf ~/.steampipe
```

Please let us know if this works / does not work / etc. Sorry for the hassle and thanks for the help tracking down this tricky timing issue!
