### ISSUE TITLE
enable inclusion of the pgvector extension

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#3484]
An app that connects a document store to an LLM backend wants to enrich its prompts by finding documents similar to a query and vectorizing them. The `pgvector` extension has emerged as one way to manage the vectors. Enabing it in Steampipe would open the door to LLM-backed apps that work with data acquired from any Steampipe plugin, use `pgvector` to manage [embeddings](https://platform.openai.com/docs/guides/embeddings/what-are-embeddings), and use the OpenAI plugin to interface to the LLM.

See also: https://supabase.com/blog/openai-embeddings-postgres-vector, https://github.com/supabase-community/nextjs-openai-doc-search

**Comment by pskrbasu** [comment]
After having an internal discussion, we decided that expanding our extensions is NOT a priority right now(especially since there is an existing Postgres way to do it for hardcore users).

We need to keep the installation as minimal as possible to keep the package size, resource requirements, and security attack surface small.
We decided that we should NOT package this extension with Steampipe, but providing a path to allow users to install extensions is reasonable.

We decided to close this issue as NOT PLANNED FOR RIGHT NOW.
