### ISSUE TITLE
Follow Semantic Versioning across all Steampipe components

### ISSUE THREAD

**Issue by electriquo** [turbot/steampipe#3618]
**Is your feature request related to a problem? Please describe.**
There are many tools that automatically updating dependencies, such as [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates). Such tools relay on [Semantic Versioning](https://semver.org/) version scheme, i.e. `MAJOR.MINOR.PATCH` as the version format.

Some of Steampipe components do not follow the Semantic Versioning scheme, and in turn dependency review tools are unable to update such dependencies. E.g. here are some components that are missing the PATCH version number
- https://github.com/turbot/steampipe-mod-aws-tags
- https://github.com/turbot/steampipe-mod-aws-compliance
- https://github.com/turbot/steampipe-mod-aws-insights
- https://github.com/turbot/steampipe-mod-aws-well-architected
- https://github.com/turbot/steampipe-mod-aws-perimeter

And this is a component that does follow the Semantic Versioning scheme
- https://github.com/turbot/steampipe
- https://github.com/turbot/steampipe-plugin-aws

**Describe the solution you'd like**
Fix the version scheme inconsistency across all Steampipe component to follow Semantic Versioning scheme

**Comment by pskrbasu** [comment]
@foolioo Thank you for the issue. Yes, we are aware of the version scheme inconsistency. We want to move over the mods to semantic versioning(which requires some work) and it is in our future milestones.

**Comment by pskrbasu** [comment]
@foolioo I'm sorry, I do not have a timeline for this RN. This has been on our plate for quite some time now and we will discuss it again in our meetings soon and get a plan to get this done.

Thanks

**Comment by pskrbasu** [comment]
@foolioo I'm sorry, we still do not have any plans to do this anytime soon.

**Comment by e-gineer** [comment]
Our mods were originally planned to use monotonic versioning “major.minor” as that seemed a better fit for their content. You can treat this pretty much the same as semantic versioning by just adding a dot zero to the end “major.minor.0” (especially since mod updates are very rarely a pure patch).

Over time we’ve settled in moving these repos to also use semantic versioning, but it hasn’t been a priority yet.

@foolioo I’m wondering why this change is important to you? What’s your specific use case?

**Comment by pskrbasu** [comment]
@electriquo 

Yes, our mod versioning is monotonic at the moment. We did work on steampipe CLI to accept semantic versioning for mods, i.e., `steampipe mod install https://github.com/turbot/steampipe-mod-aws-insights@0.10.0` would work now. 

Our mods will get updated to semantic versions with time but as @e-gineer mentioned it hasn’t been a priority yet. Thank you for raising this, since the work on CLI is done - I will go ahead and mark this as completed.

Thanks
