### ISSUE TITLE
`steampipe query` fails when there are `.sql` files in the folder

### ISSUE THREAD

**Issue by syphernl** [turbot/steampipe#554]
**Describe the bug**
I followed the installation guide, when it asked me to execute 
```bash
steampipe query "select name from steampipe_registry_plugin;"
``` 

It failed. At first it showed me SQL code from one of our own projects. Turns out there was an `*.sql` file in the folder I executed `steampipe query` from (my home directory..). After gzipping it it failed again:

```
❯ steampipe query "select name from steampipe_registry_plugin;"
Error: failed to create reflection tables: pq: syntax error at or near "hashKey"
```

Turns out I had a couple more sql files in my homedirectory. After gzipping them all the problem went away.

**Steampipe version (`steampipe -v`)**
Example: v0.5.3

**To reproduce**
Add a postgresql dump for a random database in the folder you execute `steampipe query` from.

**Expected behavior**
Steampipe to ignore those SQL files and executing on its own data set.

**Additional context**
-

**Comment by e-gineer** [comment]
Thanks for trying Steampipe @syphernl and thanks for reporting this issue.

By design, Steampipe checks the current directory for any *.sql files and then makes them available automatically for use as `query.file_name` in the interactive session. It's super convenient for rapid iteration.

But, it looks like Steampipe is refusing to start up because it cannot parse the SQL files in your directory. This is frustrating and confusing. Steampipe should give a better warning in this case and then ignore the files it cannot parse. That would keep the feature in the convenient zone, without this unexpected behavior.

We could also consider an option to disable the SQL file -> `query.*` capability.

In the meantime, as a workaround, please try running Steampipe from a directory with no SQL files, or with valid Postgres SQL files.

**Comment by syphernl** [comment]
The SQL files are valid though, they are result of a few `pg_dump` executions.

For now I'll just ensure there are no dangling `.sql` files in my home directory. 
But an option to disable the `query.*` sounds like a good one.

**Comment by kaidaguerre** [comment]
Thanks for the report @syphernl. I'm looking into this.

Could you share the name of the SQL files which are causing this error. We would not expect SQL files to cause this error, even if the files were invalid. 

Does `hashKeys` correspond to any part of the filename or contents?

**Comment by kaidaguerre** [comment]
@syphernl I have reproduced the issue - leave it with me

**Comment by kaidaguerre** [comment]
@syphernl a fix for this will be in todays release.

I have removed the failure, meaning the SQL file will be successfully loaded and available for use as a named query (I realise that is not your requirement here, but that is the default behaviour)

As @e-gineer says, we can look into making the automatic loading of SQL files optional
