### ISSUE TITLE
Add support for exiting 'steampipe query' environment with Ctrl+C shortcut

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#74]
Using Ctrl+C in my terminal for other programs allows me to exit quickly, e.g.,
```
Codys-MacBook-Pro:Desktop cbruno$ node
Welcome to Node.js v14.15.1.
Type ".help" for more information.
>
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
>
```

For `node`, it also gives me the command that I can use to exit from the environment as a helper.

Is this something that can be added while inside `steampipe query` as well?

**Comment by jhult** [comment]
@kaidaguerre, why was this reverted?

This would be nice to have.

**Comment by kaidaguerre** [comment]
Hi @jhult 

This  feature was in fact released in the latest Steampipe version, 0.5.0
https://github.com/turbot/steampipe/blob/main/CHANGELOG.md

This issue must have been overlooked and the fix was release against issue [120](https://github.com/turbot/steampipe/issues/120)

Sorry for the confusion - I will close this issue

**Comment by jhult** [comment]
@kaidaguerre, issue #120 looks like it was for cancellation of a query. For exiting the program, it `Control + C` still doesn't seem to work for me (on macOS):

![image](https://user-images.githubusercontent.com/9849069/119652180-c41efd80-bdf3-11eb-9312-22508cdd9da5.png)

**Comment by kaidaguerre** [comment]
Ah my apologies @jhult I misread the issue, as I had cancellation on my mind....

To quit the interactive session you can use `ctrl+D`. `ctrl+C` is reserved for cancellation of controls and queries.

This is consistent with psql and pgcli. On the other hand, osquery quits on `ctrl+C`, so there is not complete consistency.

Is there there a particular reason you would like `ctrl+C` instead of `ctrl+D`, or is it more a case of familiarity...?

Cheers,
Kai

**Comment by jhult** [comment]
I wasn't familiar with `ctrl+D`. For others, here is some reading about it: https://superuser.com/questions/169051/whats-the-difference-between-c-and-d-for-unix-mac-os-x-terminal/169055

To me, it would make sense that, if there isn't a query running, then `ctrl+c` quits the interactive session.
