### ISSUE TITLE
steampipe query returns 0 exit code even after the query returns ERROR

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#842]
**Describe the bug**
steampipe query returns 0 error code even after the query returns ERROR

**Steampipe version (`steampipe -v`)**
Example: v0.7.3

**To reproduce**
run a query that should fail
run echo $?
it returns 0 exit code

**Expected behavior**
should return higher exit code in case of error

**Additional context**

**Comment by chr-b** [comment]
I was about to open a similar report for `steampipe check`.

Issue #498 references the commit `steampipe check exit code should be the number of alerts`.
Actually, I don't want steampipe check to return an exit code that equals the number of alerts. I want the exit code to return whether steampipe execution was successful or not.

Maybe add an optional parameter that let's the user choose what the return code should indicate?

**Comment by e-gineer** [comment]
We've been discussing this internally as well. Would love more input...

Query cases:

| Case Ref | steampipe CLI | query result | error code|
|-|-|-|-|
| query-a | ran successfully | ran successfully | 0 |
| query-b | ran successfully | error | 0 or ? |
| query-c | failed | n/a | non-zero, ? |

Check cases:

| Case Ref | steampipe CLI | # alarms | # errors | error code |
|-|-|-|-|-|
| check-a | ran successfully | 0 | 0 | 0 |
| check-b | ran successfully | 5 | 0 | 0 or 5 or ? |
| check-c | ran successfully | 0 | 5 | 0 or 5 or ? |
| check-d | ran successfully | 5 | 5 | 0 or 5 or 10 or ? |
| check-e | failed | - | - | non-zero, ? |

Thoughts / suggestions for the exit codes for each case above?

**Comment by MichaelBurgess** [comment]
My general view is that we should always return 0 for any action that has completely successfully and >=1 for anything that hasn't. 

In this context "completed successfully" to me means the process(es) ran through to completion with no error running them and Steampipe was able to present a set of results (ignoring the semantics of what those results mean e.g. a process error and a control in "error" are different things).

So I would vote for `query-a` / `query-b` / `check-a` / `check-b` / `check-c` / `check-d` all returning `0` and `query-c` / `check-e` returning >=1, arguably `1`.

I fell foul of this the other week for a `ran successfully` check run returning a non-zero error code.

**Comment by johnsmyth** [comment]
I believe that it is useful to know that there were alarms from a `check` run (as opposed to errors) if you are using steampipe to do testing.  I think that returning the *number* of errors in the exit code is less important than that there were errors at all, because its unlikely to materially change the CI workflow  - you probably only really care if ANY tests fail.    [nunit](https://docs.nunit.org/articles/nunit/running-tests/Console-Runner.html) uses 1-100 for the number of failed tests, and different error codes (mostly negative numbers) for other errors, which is clever.  [rspec](https://relishapp.com/rspec/rspec-core/v/2-99/docs/command-line/exit-status) returns 1 if any tests fail - you can override the failure exit code, but it is not a count of errors.   There are also some ["standard" error codes](https://tldp.org/LDP/abs/html/exitcodes.html) that we should at least consider in this discussion as well.

Im a little confused by the table @e-gineer - how can a query "run successfully" but the query result is an "error" ?

**Comment by e-gineer** [comment]
@johnsmyth By that I meant that the `steampipe` executable did not fail itself, but the query was invalid (e.g. malformed SQL) and so returned an error. So steampipe successfully ran a query, but the query had an error.

**Comment by cbruno10** [comment]
This issue was addressed by https://github.com/turbot/steampipe/issues/2447.
