### ISSUE TITLE
cannot uninstall a plugin

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#852]
**Describe the bug**

Cannot uninstall a plugin

**Version**

v0.8.0

**To reproduce**

```
streampipe plugin install rss

steampipe plugin uninstall rss
```

**Expected behavior**

It's uninstalled

**Actual behavior**

*Failed to uninstall plugin, there are active connections using it*

Was running in service mode at the time, behavior survived a service shutdown. It even survived a system reboot. 

This is happening in a steampipe instance that I built from source, in WSL2.

**Comment by e-gineer** [comment]
Thanks for reporting @judell!

Can confirm that I'm seeing the same issue on Mac with the latest `main` branch `32da263`:
```
~/src/steampipe $ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
~/src/steampipe $ 
~/src/steampipe $ steampipe plugin list | grep rss
| hub.steampipe.io/plugins/turbot/rss@latest              | 0.0.2   | rss                   |
~/src/steampipe $ 
~/src/steampipe $ steampipe plugin uninstall rss
Error: Failed to uninstall plugin 'rss' - there are active connections using it: 'rss'
~/src/steampipe $ 
~/src/steampipe $ steampipe plugin list | grep rss
| hub.steampipe.io/plugins/turbot/rss@latest              | 0.0.2   | rss                   |
~/src/steampipe $ 
```

**Comment by e-gineer** [comment]
Quick update ... investigation from @binaek89 and @kaidaguerre has clarified the issue here. The "active connection" referred to means that there is a *Steampipe connection* using the plugin (as opposed to an active database connection).

If you delete the connection from your `~/.steampipe/config` directory then the uninstall should proceed without any error.

We're looking to make the error message more helpful!

**Comment by judell** [comment]
Ah, thanks, that had occurred to me and I was going to try it. Perhaps uninstall should do that for you? In any event not a big deal, I reckon uninstall is a very infrequent thing.

**Comment by judell** [comment]
Thanks @binaek and @kaidaguerre!
