### ISSUE TITLE
steampipe query immediately fails with what looks like a postgres error

### ISSUE THREAD

**Issue by danbdo** [turbot/steampipe#878]
**Describe the bug**
I installed steampipe on a Ubuntu Linux subsystem on Windows. Just went through the site's documentation. Worked well with no errors. installed the steampipe and aws plugins.
No when I just run steampipe query it fails with :

Error: failed to create reflection tables: pq: invalid byte sequence for encoding "UTF8": 0xff

**Steampipe version (`steampipe -v`)**
v0.8.0

**To reproduce**
As described above. Fresh install, trying to run steampipe query immediately fails without even allowing to run a command

**Expected behavior**
Well, just get me the input line for queries :)

**Comment by e-gineer** [comment]
Hey @danbdo ... Do you see the same error if running `steampipe query` from an empty directory?

If you have `.sql` or `.sp` files in the directory then we will try to create introspection tables for them (named queries, controls, etc). We suspect this is caused by a parsing error while building the introspection tables for mods - using an empty directory will remove that vector.

Also, any chance you could try and pull TRACE logs for us? You can do that with:
```
STEAMPIPE_LOG=trace steampipe query
```

The log should be visible in `~/.steampipe/logs/...`.

**Comment by srgg** [comment]
@kaidaguerre I can't say that exactly, sorry, but I feel like I was in teh steampipe/config directory when I've tried to start interactive query, I saw comment from e-gineer and I feel like I've checked and there was no .sp or sql files, the only spc, but I can't say that on 100% (I've tried to run it from several directories - it was failing). And now this issue is not reproduced neither from empty directory or steampipe/config.


Anyway, thank you for the quick response.

**Comment by e-gineer** [comment]
@srgg Was it failing immediately after you did the installation or upgrade? Or had you successfully run steampipe before?

Glad it seems to be working for you now ... but keen to understand anything we can about how you ended up with this issue! Thanks.

**Comment by srgg** [comment]
@e-gineer It started failing after I did 'brew upgrade' that did steampipe upgrade as well.

**Comment by dcelasun** [comment]
> If you have `.sql` or `.sp` files in the directory then we will try to create introspection tables for them (named queries, controls, etc). We suspect this is caused by a parsing error while building the introspection tables for mods - using an empty directory will remove that vector.

This was the case for me. I tried executing steampipe from `$HOME`, which contained an unrelated SQL file. Is there a environment variable or something to suppress this behaviour? In fact, it would be great to ignore any file that isn't explicitly passed to steampipe.

**Comment by e-gineer** [comment]
@dcelasun Thanks for letting us know and sorry you bumped into that edge. Agree we need to make this clearer and easier to work with... BTW, it's related to our [named queries](https://steampipe.io/docs/using-steampipe/writing-queries#named-queries) functionality.

@kaidaguerre I wonder if we could ignore files that don't compile well rather than failing? We could perhaps give a warning, but we definitely shouldn't fail in this case. It's helpful if you are expecting the SQL files to be read in as named queries, but confusing as a new user for sure.

**Comment by dcelasun** [comment]
@e-gineer thanks for that link, I wasn't aware of that functionality.

> I wonder if we could ignore files that don't compile well rather than failing?

I'd rather have an option (perhaps as an env variable so it can be placed in `.bashrc` etc) to disable such magic behaviour. It feels weird to assume a file is meant for snowpipe just because it has a `.sql` extension.
